name: Deploy Project
on: [push,workflow_dispatch] # push ve workflow_dispatch eventlerinde çalışsın. Onun için [] içinde yazıldı. Tek olsaydı [] gerek yoktu.
jobs:
  test: # 1.job ismidir. İstenilen isim verilebilir
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # Kodu almak için kullanıyoruz.
      - name: Install Nodejs
        uses: actions/setup-node@v3 # Nodejs kurulumu için kullanıyoruz.
        with:
              node-version: '18.x' # with ile Nodejs sürümünü belirtiyoruz.with ile Configuration yapıyoruz.
      - name: Install dependencies
        run: npm ci # npm install ile dependenciesleri yüklüyoruz. ci ile package-lock.json dosyasını(orada yazan versiyonları) kullanıyoruz.
      - name: Run tests
        run: npm test # npm test ile testleri çalıştırıyoruz.
  deploy: # 2.job ismidir. İstenilen isim verilebilir
    needs: test # test işlemi bittikten sonra deploy işlemi başlasın.
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
              node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Build Adımı
        run: npm run build # npm run build ile build işlemi yapıyoruz.
      - name: Deploy Adımı
        run : echo "Deploying!" # echo ile Deploying yazdırıyoruz.